# My personal Aliases
shopt -s expand_aliases

alias in="sudo apt-get install"
alias ls='clear; ls --color=auto --group-directories-first'

# Nice little prompt
PS1="docker: "

# General behaviour aliases
alias cd='_(){ cd $1; ls; }; _'
alias h="cd .."
alias c='clear'
alias s="history | grep"

# Compiler settings
alias qcc="gcc -Wall -std=c11 -g -o"
alias qc="gcc -Wall -std=c11"
alias jclean="rm *.class"
alias qpp="g++ -Wall -g -std=gnu++11 -o"
alias qp="g++ -Wall -std=gnu++11 -o"

# Git Aliases
alias u='git push -u origin master'
alias gc="git commit -am"
alias gs="git status"

# Set vim mode
set -o vi

# Find name
alias findn="find . -name"

# I always forget how to tar
alias untar="tar -vxzf"
alias maketar="tar -cvzf"

# Memory usage
alias mem="du -hsc"

# make executable
mx () {
	touch $@
	chmod u+x $@
}

# Make file/directory
alias md="mkdir"
mds () {
	mkdir $1 && cd $1
}
alias mf="touch"
alias mfr="touch readme.md"

# Git auto complete
if [ -f ~/.git-completion.bash ]; then
	. ~/.git-completion.bash
fi

# Editor
alias e="vim"
alias q="exit"
alias h="cd \$HOME/workspace"
